"""add BookingItem

Revision ID: 275ffbc41704
Revises: 05fafab59782
Create Date: 2025-03-31 22:59:38.848364

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '275ffbc41704'
down_revision = '05fafab59782'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('booking_id', sa.Integer(), nullable=True),
    sa.Column('equipment_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('users')
    op.drop_table('bookings')
    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('category',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('subcategory',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=True)

    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('start_hour',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('end_hour',
               existing_type=mysql.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('schedule', schema=None) as batch_op:
        batch_op.alter_column('end_hour',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_hour',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=mysql.INTEGER(),
               nullable=False)

    with op.batch_alter_table('equipment', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('quantity',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('subcategory',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50),
               nullable=False)

    op.create_table('bookings',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('equipment_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('hour', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], name='bookings_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='bookings_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=20), nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('password', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=128), nullable=False),
    sa.Column('role', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.drop_table('booking_item')
    op.drop_table('booking')
    op.drop_table('user')
    # ### end Alembic commands ###
